/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 goatloaf_scene.glb --transform --instance --types
*/

// @ts-nocheck

import * as THREE from "three";
import React, { useRef, useMemo, useContext, createContext } from "react";
import { useGLTF, Merged, useVideoTexture, MeshReflectorMaterial, PerspectiveCamera, RenderTexture } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { SpinningBox } from "./SpinningBox";

// do types for screenContent

type ScreenContent = {
  type: "video" | "scene" | "image";
  src: string;
};

const screenContent: Record<string, ScreenContent> = {
  middleScreen: {
    type: "video",
    src: "backrooms_logo.webm",
  },
  middleUpperScreen: {
    type: "scene",
    src: "box",
  },
  rightMiddleScreen: {
    type: "video",
    src: "animation_compressed.mp4",
  },
  rightUpperScreen: {
    type: "video",
    src: "backrooms.webm",
  },
  leftUpperScreen: {
    type: "video",
    src: "sonic_genesis.mp4",
  },
  leftLeftScreen: {
    type: "video",
    src: "sonic_genesis.mp4",
  },
  leftRightScreen: {
    type: "video",
    src: "animation_compressed.mp4",
  },
};

type GLTFResult = GLTF & {
  nodes: {
    ["#APL0002_Back_#APL0002_Detail_0"]: THREE.Mesh;
    ["#APL0002_Balance_#APL0002_Detail_0"]: THREE.Mesh;
    ["#APL0002_Deck_A_#APL0002_Acrylic_Glass_0"]: THREE.Mesh;
    ["#APL0002_Deck_A_#APL0002_Detail_0"]: THREE.Mesh;
    ["#APL0002_Deck_B_#APL0002_Acrylic_Glass_0"]: THREE.Mesh;
    ["#APL0002_Deck_B_#APL0002_Detail_0"]: THREE.Mesh;
    ["#APL0002_Deck_Selector_#APL0002_Detail_0"]: THREE.Mesh;
    ["#APL0002_Dolby_NR_#APL0002_Detail_0"]: THREE.Mesh;
    ["#APL0002_Dubbing_High_#APL0002_Detail_0"]: THREE.Mesh;
    ["#APL0002_Dubbing_Normal_#APL0002_Detail_0"]: THREE.Mesh;
    ["#APL0002_Eject_A_#APL0002_Detail_0"]: THREE.Mesh;
    ["#APL0002_Eject_B_#APL0002_Detail_0"]: THREE.Mesh;
    ["#APL0002_FF_#APL0002_Detail_0"]: THREE.Mesh;
    ["#APL0002_Front_#APL0002_Detail_0"]: THREE.Mesh;
    ["#APL0002_Mute_Search_#APL0002_Detail_0"]: THREE.Mesh;
    ["#APL0002_Play_#APL0002_Detail_0"]: THREE.Mesh;
    ["#APL0002_Power_#APL0002_Detail_0"]: THREE.Mesh;
    ["#APL0002_Rec_Level_#APL0002_Detail_0"]: THREE.Mesh;
    ["#APL0002_Rec_Pause_#APL0002_Detail_0"]: THREE.Mesh;
    ["#APL0002_Rewind_#APL0002_Detail_0"]: THREE.Mesh;
    ["#APL0002_Spindle_A_01_#APL0002_Detail_0"]: THREE.Mesh;
    ["#APL0002_Spindle_A_02_#APL0002_Detail_0"]: THREE.Mesh;
    ["#APL0002_Spindle_B_01_#APL0002_Detail_0"]: THREE.Mesh;
    ["#APL0002_Spindle_B_02_#APL0002_Detail_0"]: THREE.Mesh;
    ["#APL0002_Stop_#APL0002_Detail_0"]: THREE.Mesh;
    ["#APL0002_Tape_Counter_001_#APL0002_Detail_0"]: THREE.Mesh;
    ["#APL0002_Tape_Counter_010_#APL0002_Detail_0"]: THREE.Mesh;
    ["#APL0002_Tape_Counter_100_#APL0002_Detail_0"]: THREE.Mesh;
    ["#APL0002_Tape_Counter_Reset_#APL0002_Detail_0"]: THREE.Mesh;
    ["#APL0002_Timer_#APL0002_Detail_0"]: THREE.Mesh;
    ["#APL0002_Cassette_Deck_Yamaha_KX-W202_#APL0002_Body_0"]: THREE.Mesh;
    Object_4001: THREE.Mesh;
    Object_7: THREE.Mesh;
    Object_9: THREE.Mesh;
    Object_11: THREE.Mesh;
    Object_13: THREE.Mesh;
    Object_5: THREE.Mesh;
    Object_17: THREE.Mesh;
    Object_15: THREE.Mesh;
    Cube_back_0: THREE.Mesh;
    Cube_screen_0: THREE.Mesh;
    Cube_side_0: THREE.Mesh;
    Object_2001: THREE.Mesh;
    Object_3001: THREE.Mesh;
    Object009_M_PS2_Body_0: THREE.Mesh;
    PS2_Body_M_PS2_Details_0: THREE.Mesh;
    PS2_Details_M_PS2_Details_0: THREE.Mesh;
    Object_19: THREE.Mesh;
    Object_20: THREE.Mesh;
    Object_21: THREE.Mesh;
    Object_22: THREE.Mesh;
    Object_23: THREE.Mesh;
    Button_01_low003_Material_01_0: THREE.Mesh;
    Button_02_low003_Material_01_0: THREE.Mesh;
    Button_03_low003_Material_01_0: THREE.Mesh;
    Circle_02_low003_Material_01_0: THREE.Mesh;
    Corps_01_low014_Material_01_0: THREE.Mesh;
    Corps_01_low015_Material_01_0: THREE.Mesh;
    Corps_01_low016_Material_01_0: THREE.Mesh;
    Element_01_low003_Material_01_0: THREE.Mesh;
    Metal_thread_01_low003_Material_01_0: THREE.Mesh;
    Sphere_01_low003_Material_01_0: THREE.Mesh;
    Sphere_02_low003_Material_01_0: THREE.Mesh;
    Sphere_03_low003_Material_01_0: THREE.Mesh;
    Sphere_04_low003_Material_01_0: THREE.Mesh;
    Sphere_05_low003_Material_01_0: THREE.Mesh;
    Sphere_06_low003_Material_01_0: THREE.Mesh;
    Sphere_07_low003_Material_01_0: THREE.Mesh;
    Sphere_08_low003_Material_01_0: THREE.Mesh;
    Sphere_09_low003_Material_01_0: THREE.Mesh;
    Sphere_10_low003_Material_01_0: THREE.Mesh;
    Sphere_11_low003_Material_01_0: THREE.Mesh;
    Sphere_12_low003_Material_01_0: THREE.Mesh;
    Sphere_13_low003_Material_01_0: THREE.Mesh;
    Sphere_14_low003_Material_01_0: THREE.Mesh;
    Sphere_15_low003_Material_01_0: THREE.Mesh;
    Sphere_16_low003_Material_01_0: THREE.Mesh;
    Sphere_17_low003_Material_01_0: THREE.Mesh;
    Sphere_18_low003_Material_01_0: THREE.Mesh;
    Sphere_19_low003_Material_01_0: THREE.Mesh;
    Sphere_20_low003_Material_01_0: THREE.Mesh;
    Sphere_22_low003_Material_01_0: THREE.Mesh;
    Sphere_23_low003_Material_01_0: THREE.Mesh;
    Sphere_24_low003_Material_01_0: THREE.Mesh;
    Sphere_25_low003_Material_01_0: THREE.Mesh;
    Sphere_26_low003_Material_01_0: THREE.Mesh;
    Sphere_27_low003_Material_01_0: THREE.Mesh;
    Sphere_28_low003_Material_01_0: THREE.Mesh;
    Cube001_Material007_0: THREE.Mesh;
    Cube001_Material007_0001: THREE.Mesh;
    Cube001_Material007_0002: THREE.Mesh;
    Cube001_Material_0: THREE.Mesh;
    Plane_Material006_0: THREE.Mesh;
    Plane001_Material006_0: THREE.Mesh;
    Plane002_Material006_0: THREE.Mesh;
    Plane003_Material006_0: THREE.Mesh;
    Plane004_Material006_0: THREE.Mesh;
    Plane005_Material006_0: THREE.Mesh;
    Plane006_Material006_0: THREE.Mesh;
    Plane007_Material006_0: THREE.Mesh;
    Object_471: THREE.Mesh;
    Object_477: THREE.Mesh;
    Object_479: THREE.Mesh;
    Object_481: THREE.Mesh;
    Object_483: THREE.Mesh;
    Object_485: THREE.Mesh;
    Object_487: THREE.Mesh;
    Object_489: THREE.Mesh;
    Object_491: THREE.Mesh;
    Object_493: THREE.Mesh;
    Object_159: THREE.Mesh;
    Object_161: THREE.Mesh;
    Object_163: THREE.Mesh;
    Object_165: THREE.Mesh;
    Object_167: THREE.Mesh;
    Object_169: THREE.Mesh;
    Object_174: THREE.Mesh;
    Object_176: THREE.Mesh;
    Object_178: THREE.Mesh;
    Object_180: THREE.Mesh;
    Object_182: THREE.Mesh;
    Object_184: THREE.Mesh;
    Object_186: THREE.Mesh;
    Object_188: THREE.Mesh;
    Object_194: THREE.Mesh;
    Object_196: THREE.Mesh;
    Object_198: THREE.Mesh;
    Object_200: THREE.Mesh;
    Object_202: THREE.Mesh;
    Object_204: THREE.Mesh;
    Object_206: THREE.Mesh;
    Object_212: THREE.Mesh;
    Object_214: THREE.Mesh;
    Object_216: THREE.Mesh;
    Object_218: THREE.Mesh;
    Object_220: THREE.Mesh;
    Object_222: THREE.Mesh;
    Object_224: THREE.Mesh;
    Object_226: THREE.Mesh;
    Object_228: THREE.Mesh;
    Object_230: THREE.Mesh;
    Object_232: THREE.Mesh;
    Object_234: THREE.Mesh;
    Object_236: THREE.Mesh;
    Object_238: THREE.Mesh;
    Object_240: THREE.Mesh;
    Object_242: THREE.Mesh;
    Object_244: THREE.Mesh;
    Object_246: THREE.Mesh;
    Object_248: THREE.Mesh;
    Object_250: THREE.Mesh;
    Object_252: THREE.Mesh;
    Object_254: THREE.Mesh;
    Object_256: THREE.Mesh;
    Object_258: THREE.Mesh;
    Object_260: THREE.Mesh;
    Object_262: THREE.Mesh;
    Object_264: THREE.Mesh;
    Object_268: THREE.Mesh;
    Object_270: THREE.Mesh;
    Object_274: THREE.Mesh;
    Object_276: THREE.Mesh;
    Object_278: THREE.Mesh;
    Object_284: THREE.Mesh;
    Object_286: THREE.Mesh;
    Object_288: THREE.Mesh;
    Object_290: THREE.Mesh;
    Object_292: THREE.Mesh;
    Object_294: THREE.Mesh;
    Object_296: THREE.Mesh;
    Object_453: THREE.Mesh;
    Object_455: THREE.Mesh;
    Object_461: THREE.Mesh;
    Object_208: THREE.Mesh;
    Object_210: THREE.Mesh;
    Object_171: THREE.Mesh;
    Object_172: THREE.Mesh;
    Object_190: THREE.Mesh;
    Object_192: THREE.Mesh;
    Object_272: THREE.Mesh;
    Object_280: THREE.Mesh;
    Object_266: THREE.Mesh;
    Object_282: THREE.Mesh;
    Cube011_0: THREE.Mesh;
    Cube011_1: THREE.Mesh;
    Cube011_2: THREE.Mesh;
    Cube011_4: THREE.Mesh;
    Cube011_5: THREE.Mesh;
    Cube011_6: THREE.Mesh;
    Cube011_7: THREE.Mesh;
    Cube008_0: THREE.Mesh;
    Cube008_1: THREE.Mesh;
    Cube008_4: THREE.Mesh;
    Cube008_5: THREE.Mesh;
    Cube008_6: THREE.Mesh;
    Cube008_7: THREE.Mesh;
    Cube008_2: THREE.Mesh;
    Cube012_0: THREE.Mesh;
    Cube012_1: THREE.Mesh;
    Cube012_4: THREE.Mesh;
    Cube012_5: THREE.Mesh;
    Cube012_6: THREE.Mesh;
    Cube012_7: THREE.Mesh;
    Cube012_2: THREE.Mesh;
    Cube027_0: THREE.Mesh;
    Cube027_1: THREE.Mesh;
    Cube027_2: THREE.Mesh;
    Cube027_3: THREE.Mesh;
    Cube027_4: THREE.Mesh;
    Cube027_5: THREE.Mesh;
    Cube027_6: THREE.Mesh;
    Cube027_7: THREE.Mesh;
    Cube027_8: THREE.Mesh;
    BigTVScreen: THREE.Mesh;
    Cube051_0: THREE.Mesh;
    Cube051_1: THREE.Mesh;
    Cube051_2: THREE.Mesh;
    Cube051_3: THREE.Mesh;
    Cube051_5: THREE.Mesh;
    Cube051_6: THREE.Mesh;
    Cube051_7: THREE.Mesh;
    Cube052_0: THREE.Mesh;
    Cube052_1: THREE.Mesh;
    Cube052_2: THREE.Mesh;
    Cube009_0: THREE.Mesh;
    Cube009_1: THREE.Mesh;
    Cube009_2: THREE.Mesh;
    Cylinder_0: THREE.Mesh;
    Cylinder_1: THREE.Mesh;
    Cylinder_2: THREE.Mesh;
    Cylinder_3: THREE.Mesh;
    Cylinder_4: THREE.Mesh;
    Cylinder_5001: THREE.Mesh;
    Cube007_0: THREE.Mesh;
    Cube007_1: THREE.Mesh;
    Cube007_2: THREE.Mesh;
    Cube007_3: THREE.Mesh;
    defaultMaterial006: THREE.Mesh;
    defaultMaterial005: THREE.Mesh;
    defaultMaterial007: THREE.Mesh;
    defaultMaterial002: THREE.Mesh;
    defaultMaterial001: THREE.Mesh;
    defaultMaterial008: THREE.Mesh;
    defaultMaterial: THREE.Mesh;
    defaultMaterial003: THREE.Mesh;
    defaultMaterial004: THREE.Mesh;
    ["Bool��en_Mat3_0"]: THREE.Mesh;
    ["Bool��en_1_Mat3_0"]: THREE.Mesh;
    Cylindre_Mat3_0: THREE.Mesh;
    Cylindre_1_Mat3_0: THREE.Mesh;
    Cylindre_2_Mat3_0: THREE.Mesh;
    Cylindre_2_2_Mat3_0: THREE.Mesh;
    ["Extrusion_contr��l��e_Mat3_0"]: THREE.Mesh;
    ["Extrusion_contr��l��e_1_Mat3_0"]: THREE.Mesh;
    Cube_Mat6_0: THREE.Mesh;
    Cube_1_2_Mat3_0: THREE.Mesh;
    Cube_2_Mat3_0: THREE.Mesh;
    ["Cube_2_2_Mat6_(converted)_(converted_from_U-Render)_0"]: THREE.Mesh;
    ["Cube_3_Mat6_(converted)_(converted_from_U-Render)_0"]: THREE.Mesh;
    Cube_4_Mat12_0: THREE.Mesh;
    Cube_5_Mat3_0: THREE.Mesh;
    Cube_6_VOLUME_0: THREE.Mesh;
    Cube_7_Cylindre_11_Mat3_0: THREE.Mesh;
    Cube_Cloneur_Cu_1_Extrusion_Cube_Cube_Mat3_0: THREE.Mesh;
    Cube_Cloneur_Cu_Ext_Mat3_0: THREE.Mesh;
    Cube_Cloneur_Cu_Extrusio_Mat3_0: THREE.Mesh;
    Cube_Cloneur_Cu_Extrusion_Cube_1_Extrusion_1_Mat3_0: THREE.Mesh;
    Cube_Cloneur_Cu_Extrusion_Cube_4_Extrusion_1_Cube_Mat6_0: THREE.Mesh;
    Cube_Cloneur_Cube_Extrusion_1_Cube_1_Mat1_0: THREE.Mesh;
    Cylindre_10_VOLUME_0: THREE.Mesh;
    Cylindre_11_Mat4_0: THREE.Mesh;
    Cylindre_1_Extrusion_Cube_Mat3_0: THREE.Mesh;
    Cylindre_1_Extrusion_Cube_1_Extrusion_4_Mat3_0: THREE.Mesh;
    Cylindre_2_4_Mat3_0: THREE.Mesh;
    Cylindre_3_Mat3_0: THREE.Mesh;
    Cylindre_4_Mat3_0: THREE.Mesh;
    ["Cylindre_4_3_Mat6_(converted)_(converted_from_U-Render)_0"]: THREE.Mesh;
    Cylindre_5_Mat3_0: THREE.Mesh;
    Cylindre_9_Mat4_0: THREE.Mesh;
    Cylindre_Cylindre_10_Mat4_0: THREE.Mesh;
    Cylindre_Extrusion_1_Mat4_0: THREE.Mesh;
    Extrusion_1_2_Mat3_0: THREE.Mesh;
    Extrusion_2_Mat3_0: THREE.Mesh;
    Extrusion_2_2_Mat3_0: THREE.Mesh;
    Extrusion_3_Mat3_0: THREE.Mesh;
    Extrusion_4_Mat3_0: THREE.Mesh;
    Extrusion_5_Mat3_0: THREE.Mesh;
    Extrusion_6_Mat3_0: THREE.Mesh;
    Extrusion_6_Cube_Mat3_0: THREE.Mesh;
    Extrusion_6_Cube_6_Mat3_0: THREE.Mesh;
    ["Extrusion_contr��l��e_1_2_Mat3_0"]: THREE.Mesh;
    Extrusion_Cylindre_Mat3_0: THREE.Mesh;
    Extrusion_Extrusion_1_E_Cloneur_Mat3_0: THREE.Mesh;
    PCB_Mat5_0: THREE.Mesh;
    PCB_1_Mat9_0: THREE.Mesh;
    TOUCHE_6128_Mat2_0: THREE.Mesh;
    Object_27: THREE.Mesh;
    Object_11003: THREE.Mesh;
    Object_32001: THREE.Mesh;
    Object_33: THREE.Mesh;
    Object_35001: THREE.Mesh;
    Object_37: THREE.Mesh;
    Object_38001: THREE.Mesh;
    Object_25: THREE.Mesh;
    Object_21001: THREE.Mesh;
    Object_16001: THREE.Mesh;
    Object_4: THREE.Mesh;
    Object_5003: THREE.Mesh;
    Object_23002: THREE.Mesh;
    Object_13001: THREE.Mesh;
    Object_14002: THREE.Mesh;
    Object_18: THREE.Mesh;
    Object_19001: THREE.Mesh;
    Object_7002: THREE.Mesh;
    Object_29001: THREE.Mesh;
    Object_30: THREE.Mesh;
    Object_9001: THREE.Mesh;
    ["Plane008_02_-_Default_0"]: THREE.Mesh;
    ["Plane008_09_-_Default_0"]: THREE.Mesh;
    Plane008_default_0: THREE.Mesh;
    defaultMaterial012: THREE.Mesh;
    defaultMaterial011: THREE.Mesh;
    Cylinder_1_0: THREE.Mesh;
    Cylinder_1_0001: THREE.Mesh;
    Cable: THREE.Mesh;
  };
  materials: {
    APL0002_Detail: THREE.MeshStandardMaterial;
    APL0002_Acrylic_Glass: THREE.MeshPhysicalMaterial;
    APL0002_Body: THREE.MeshStandardMaterial;
    material: THREE.MeshStandardMaterial;
    ["Material.002"]: THREE.MeshStandardMaterial;
    ["Material.003"]: THREE.MeshStandardMaterial;
    ["Material.001"]: THREE.MeshStandardMaterial;
    ["Material.005"]: THREE.MeshStandardMaterial;
    Material: THREE.MeshStandardMaterial;
    ["Material.006"]: THREE.MeshStandardMaterial;
    ["Material.004"]: THREE.MeshStandardMaterial;
    back: THREE.MeshStandardMaterial;
    screen: THREE.MeshPhysicalMaterial;
    side: THREE.MeshStandardMaterial;
    Pi_Lowpoly: THREE.MeshStandardMaterial;
    M_PS2_Body: THREE.MeshStandardMaterial;
    M_PS2_Details: THREE.MeshStandardMaterial;
    ["Material.015"]: THREE.MeshStandardMaterial;
    ["Material.011"]: THREE.MeshStandardMaterial;
    ["Material.016"]: THREE.MeshStandardMaterial;
    ["Material.007"]: THREE.MeshStandardMaterial;
    ["Material.010"]: THREE.MeshStandardMaterial;
    Material_01: THREE.MeshStandardMaterial;
    ["Material.017"]: THREE.MeshStandardMaterial;
    ["Material.018"]: THREE.MeshStandardMaterial;
    ["Material.019"]: THREE.MeshStandardMaterial;
    ["Material.048"]: THREE.MeshStandardMaterial;
    ["Material.036"]: THREE.MeshStandardMaterial;
    ["Material.022"]: THREE.MeshStandardMaterial;
    ["Material.026"]: THREE.MeshStandardMaterial;
    ["Material.051"]: THREE.MeshStandardMaterial;
    ["Material.066"]: THREE.MeshStandardMaterial;
    ["Material.067"]: THREE.MeshStandardMaterial;
    ["Material.049"]: THREE.MeshStandardMaterial;
    ["Material.025"]: THREE.MeshStandardMaterial;
    ["Material.037"]: THREE.MeshStandardMaterial;
    ["Material.038"]: THREE.MeshStandardMaterial;
    ["Material.039"]: THREE.MeshStandardMaterial;
    ["Material.040"]: THREE.MeshStandardMaterial;
    ["Material.041"]: THREE.MeshStandardMaterial;
    ["Material.042"]: THREE.MeshStandardMaterial;
    ["Material.044"]: THREE.MeshStandardMaterial;
    material_0: THREE.MeshStandardMaterial;
    ["Material.032"]: THREE.MeshStandardMaterial;
    ["Material.047"]: THREE.MeshStandardMaterial;
    ["Material.023"]: THREE.MeshStandardMaterial;
    ["Material.021"]: THREE.MeshStandardMaterial;
    ["Material.043"]: THREE.MeshStandardMaterial;
    ["Material.030"]: THREE.MeshStandardMaterial;
    ["Material.050"]: THREE.MeshStandardMaterial;
    ["Material.046"]: THREE.MeshStandardMaterial;
    SCREEN: THREE.MeshStandardMaterial;
    ["Material.071"]: THREE.MeshStandardMaterial;
    ["Material.068"]: THREE.MeshStandardMaterial;
    SCREEN: THREE.MeshStandardMaterial;
    ["Material.070"]: THREE.MeshStandardMaterial;
    ["Material.069"]: THREE.MeshStandardMaterial;
    ["Material.073"]: THREE.MeshStandardMaterial;
    ["Material.072"]: THREE.MeshStandardMaterial;
    ["Material.074"]: THREE.MeshStandardMaterial;
    ["Material.075"]: THREE.MeshStandardMaterial;
    ["Material.076"]: THREE.MeshStandardMaterial;
    ["Material.088"]: THREE.MeshStandardMaterial;
    ["Material.097"]: THREE.MeshStandardMaterial;
    ["Material.081"]: THREE.MeshStandardMaterial;
    ["Material.089"]: THREE.MeshStandardMaterial;
    ["Material.090"]: THREE.MeshStandardMaterial;
    ["Material.091"]: THREE.MeshPhysicalMaterial;
    ["Material.092"]: THREE.MeshStandardMaterial;
    ["Material.086"]: THREE.MeshStandardMaterial;
    TVfront: THREE.MeshStandardMaterial;
    TVback: THREE.MeshStandardMaterial;
    TVScreen: THREE.MeshStandardMaterial;
    ["Mat.3_0"]: THREE.MeshStandardMaterial;
    ["Mat.3"]: THREE.MeshStandardMaterial;
    ["Mat.6_0"]: THREE.MeshStandardMaterial;
    ["Mat.6_converted_converted_from_U-Render_1"]: THREE.MeshStandardMaterial;
    ["Mat.12"]: THREE.MeshStandardMaterial;
    VOLUME: THREE.MeshStandardMaterial;
    ["Mat.6"]: THREE.MeshStandardMaterial;
    ["Mat.1"]: THREE.MeshStandardMaterial;
    ["Mat.4"]: THREE.MeshStandardMaterial;
    ["Mat.6_converted_converted_from_U-Render_0"]: THREE.MeshStandardMaterial;
    ["Mat.5"]: THREE.MeshStandardMaterial;
    ["Mat.9"]: THREE.MeshStandardMaterial;
    ["Mat.2"]: THREE.MeshStandardMaterial;
    Metal2: THREE.MeshStandardMaterial;
    MainPCB: THREE.MeshStandardMaterial;
    ["Material.100"]: THREE.MeshStandardMaterial;
    RedWire: THREE.MeshStandardMaterial;
    BlackWire: THREE.MeshStandardMaterial;
    MetalTubes: THREE.MeshStandardMaterial;
    BackPCB: THREE.MeshStandardMaterial;
    ["Material.098"]: THREE.MeshStandardMaterial;
    ["Material.099"]: THREE.MeshStandardMaterial;
    ["02_-_Default"]: THREE.MeshStandardMaterial;
    ["09_-_Default"]: THREE.MeshStandardMaterial;
    ["default"]: THREE.MeshStandardMaterial;
    ["kropp.001"]: THREE.MeshStandardMaterial;
    ["Knappar.001"]: THREE.MeshStandardMaterial;
    ["material.001"]: THREE.MeshStandardMaterial;
  };
};

const context = createContext();
export function Instances({ children, ...props }) {
  const { nodes } = useGLTF("/goatloaf_scene-transformed.glb") as GLTFResult;
  const instances = useMemo(
    () => ({
      APLBalanceAPLDetail: nodes["#APL0002_Balance_#APL0002_Detail_0"],
      APLDeckSelectorAPLDetail: nodes["#APL0002_Deck_Selector_#APL0002_Detail_0"],
      APLEjectAAPLDetail: nodes["#APL0002_Eject_A_#APL0002_Detail_0"],
      APLFFAPLDetail: nodes["#APL0002_FF_#APL0002_Detail_0"],
      APLPlayAPLDetail: nodes["#APL0002_Play_#APL0002_Detail_0"],
      APLSpindleAAPLDetail: nodes["#APL0002_Spindle_A_01_#APL0002_Detail_0"],
      APLTapeCounterAPLDetail: nodes["#APL0002_Tape_Counter_001_#APL0002_Detail_0"],
      PlaneMaterial: nodes.Plane_Material006_0,
      Object88: nodes.Object_208,
      Cube: nodes.Cube011_0,
      Cube1: nodes.Cube011_1,
      Cube3: nodes.Cube011_4,
      Cube4: nodes.Cube011_5,
      Cube5: nodes.Cube011_6,
      Cube6: nodes.Cube011_7,
      BoolenMat: nodes["Bool��en_Mat3_0"],
      CylindreMat: nodes.Cylindre_Mat3_0,
    }),
    [nodes]
  );
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => <context.Provider value={instances} children={children} />}
    </Merged>
  );
}

export function Model(props: JSX.IntrinsicElements["group"]) {
  const instances = useContext(context);
  const { nodes, materials } = useGLTF("/goatloaf_scene-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      {/* Cassette Player - Heavy */}
      {/* <group position={[3.77, 7.36, 0.38]} rotation={[-Math.PI / 2, 0, -2.83]} scale={[10.12, 9.42, 9.02]}>
        <group position={[-0.1, -0.12, 0.02]}>
          <mesh geometry={nodes['#APL0002_Deck_A_#APL0002_Acrylic_Glass_0'].geometry} material={materials.APL0002_Acrylic_Glass} />
          <mesh geometry={nodes['#APL0002_Deck_A_#APL0002_Detail_0'].geometry} material={materials.APL0002_Detail} />
        </group>
        <group position={[0.14, -0.12, 0.02]}>
          <mesh geometry={nodes['#APL0002_Deck_B_#APL0002_Acrylic_Glass_0'].geometry} material={materials.APL0002_Acrylic_Glass} />
          <mesh geometry={nodes['#APL0002_Deck_B_#APL0002_Detail_0'].geometry} material={materials.APL0002_Detail} />
        </group>
        <mesh geometry={nodes['#APL0002_Cassette_Deck_Yamaha_KX-W202_#APL0002_Body_0'].geometry} material={materials.APL0002_Body} />
        <mesh geometry={nodes['#APL0002_Back_#APL0002_Detail_0'].geometry} material={materials.APL0002_Detail} position={[0, 0.12, 0.06]} />
        <instances.APLBalanceAPLDetail position={[0.01, -0.13, 0.03]} />
        <instances.APLDeckSelectorAPLDetail position={[0.05, -0.13, 0.07]} />
        <instances.APLBalanceAPLDetail position={[-0.02, -0.13, 0.03]} />
        <instances.APLDeckSelectorAPLDetail position={[0.06, -0.13, 0.05]} />
        <instances.APLDeckSelectorAPLDetail position={[0.04, -0.13, 0.05]} />
        <instances.APLEjectAAPLDetail position={[-0.19, -0.13, 0.03]} />
        <instances.APLEjectAAPLDetail position={[0.06, -0.13, 0.03]} />
        <instances.APLFFAPLDetail position={[0.02, -0.13, 0.08]} />
        <mesh geometry={nodes['#APL0002_Front_#APL0002_Detail_0'].geometry} material={materials.APL0002_Detail} position={[-0.03, -0.13, 0.09]} />
        <instances.APLFFAPLDetail position={[0.02, -0.13, 0.06]} />
        <instances.APLPlayAPLDetail position={[0, -0.13, 0.08]} />
        <mesh geometry={nodes['#APL0002_Power_#APL0002_Detail_0'].geometry} material={materials.APL0002_Detail} position={[-0.19, -0.13, 0.09]} />
        <instances.APLBalanceAPLDetail position={[0.03, -0.13, 0.03]} />
        <instances.APLFFAPLDetail position={[-0.03, -0.13, 0.06]} />
        <instances.APLFFAPLDetail position={[-0.03, -0.13, 0.08]} />
        <instances.APLSpindleAAPLDetail position={[-0.12, -0.1, 0.07]} rotation={[0, 0.83, 0]} />
        <instances.APLSpindleAAPLDetail position={[-0.08, -0.1, 0.07]} />
        <instances.APLSpindleAAPLDetail position={[0.12, -0.1, 0.07]} rotation={[-Math.PI, 1.5, -Math.PI]} />
        <instances.APLSpindleAAPLDetail position={[0.16, -0.1, 0.07]} rotation={[0, 0.47, 0]} />
        <instances.APLPlayAPLDetail position={[0, -0.13, 0.06]} />
        <instances.APLTapeCounterAPLDetail position={[-0.02, -0.13, 0.09]} />
        <instances.APLTapeCounterAPLDetail position={[-0.02, -0.13, 0.09]} />
        <instances.APLTapeCounterAPLDetail position={[-0.03, -0.13, 0.09]} />
        <mesh geometry={nodes['#APL0002_Tape_Counter_Reset_#APL0002_Detail_0'].geometry} material={materials.APL0002_Detail} position={[-0.01, -0.13, 0.09]} />
        <mesh geometry={nodes['#APL0002_Timer_#APL0002_Detail_0'].geometry} material={materials.APL0002_Detail} position={[-0.2, -0.13, 0.05]} />
      </group> */}
      {/* VHS Tape - Tiny */}
      <group position={[-6.61, 8.19, -2.47]} rotation={[-Math.PI / 2, 0, -2.48]} scale={0.42}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_4001.geometry} material={materials.material} position={[-0.01, -1.71, 2.4]} />
        </group>
      </group>
      {/* Desk */}
      <group position={[0, 7.32, 0]} rotation={[-Math.PI / 2, 0, 3.14]} scale={1.52}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, -4.81, 0]}>
            {/* <mesh geometry={nodes.Object_7.geometry} material={materials['Material.002']} position={[0, 3.83, -1.54]} rotation={[0, -1.57, 0]} scale={[0.07, 1.37, 5]} /> */}
            {/* <mesh geometry={nodes.Object_9.geometry} material={materials['Material.003']} position={[0, 4.65, -0.32]} scale={[0.01, 0.01, 1.29]} /> */}
            {/* <mesh geometry={nodes.Object_11.geometry} material={materials['Material.001']} position={[0, 0.08, -0.49]} scale={0.06} /> */}
            {/* <mesh geometry={nodes.Object_13.geometry} material={materials['Material.005']} position={[0, 0.08, -1.81]} scale={0.07} /> */}
            {/* <mesh geometry={nodes.Object_5.geometry} material={materials['Material.004']} position={[0, 4.81, 0]} scale={[6.04, 0.06, 2.64]} /> */}
            <mesh receiveShadow rotation={[-Math.PI / 2, 0, 0]} position={[0, 4.83, 0]}>
              <planeGeometry args={[10, 10]} />
              {/* <meshStandardMaterial color='#ffffff' /> */}
              <MeshReflectorMaterial
                blur={[300, 30]}
                resolution={2048}
                mixBlur={1}
                mixStrength={80}
                roughness={1}
                depthScale={1.2}
                minDepthThreshold={0.4}
                maxDepthThreshold={1.4}
                color="#202020"
                metalness={0.8}
              />
            </mesh>
            {/* <mesh geometry={nodes.Object_17.geometry} material={materials['Material.006']} position={[0, 4.87, -1.55]} scale={0.03} /> */}
            {/* <mesh geometry={nodes.Object_15.geometry} material={materials['Material.004']} position={[0, 2.44, -1.55]} scale={[0.06, 1, 0.06]} /> */}
          </group>
        </group>
      </group>
      {/* IDK */}
      {/* <group position={[1.46, 7.55, -3.08]} rotation={[-0.17, 0.86, -3.01]} scale={0}>
        <group position={[-89.01, -25.51, 0]} scale={[44.74, 21.86, 44.74]}>
          <mesh geometry={nodes.Cube_back_0.geometry} material={materials.back} />
          <mesh geometry={nodes.Cube_screen_0.geometry} material={materials.screen} />
          <mesh geometry={nodes.Cube_side_0.geometry} material={materials.side} />
        </group>
      </group> */}
      {/* Raspberry Pi Zero - Small */}
      {/* <group position={[2.24, 7.47, -1.36]} rotation={[-Math.PI / 2, 0, -2.36]} scale={24.59}>
        <mesh geometry={nodes.Object_2001.geometry} material={materials.Pi_Lowpoly} />
        <mesh geometry={nodes.Object_3001.geometry} material={materials.Pi_Lowpoly} />
      </group> */}
      {/* PS2 - Tiny */}
      <group position={[-4.23, 7.41, -2.9]} rotation={[-Math.PI / 2, 0, 2.87]} scale={7.53}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh geometry={nodes.Object009_M_PS2_Body_0.geometry} material={materials.M_PS2_Body} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.PS2_Body_M_PS2_Details_0.geometry} material={materials.M_PS2_Details} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh
            geometry={nodes.PS2_Details_M_PS2_Details_0.geometry}
            material={materials.M_PS2_Details}
            position={[0, 0, 0.03]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
        </group>
      </group>
      {/* Hard Drive Disk - Tiny */}
      {/* <group position={[-5.99, 7.61, -3.21]} rotation={[-Math.PI / 2, 0, -1.55]} scale={0.15}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[4.8, -1.04, 2.09]} rotation={[-Math.PI, -0.73, 0]} scale={[1.62, 1.62, 2.39]}>
            <mesh geometry={nodes.Object_19.geometry} material={materials['Material.015']} />
            <mesh geometry={nodes.Object_20.geometry} material={materials['Material.011']} />
            <mesh geometry={nodes.Object_21.geometry} material={materials['Material.016']} />
            <mesh geometry={nodes.Object_22.geometry} material={materials['Material.007']} />
            <mesh geometry={nodes.Object_23.geometry} material={materials['Material.010']} />
          </group>
        </group>
      </group> */}
      {/* IDK - Tiny */}
      <group position={[2.06, 7.43, -0.71]} rotation={[-1.22, -0.2, 0.2]} scale={6.35}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0}>
          <group position={[0.01, 35.34, 0.49]} rotation={[-Math.PI / 2, 0.09, 0]}>
            <group rotation={[-0.06, 0.17, 0.7]}>
              <mesh
                geometry={nodes.Element_01_low003_Material_01_0.geometry}
                material={materials.Material_01}
                position={[-21.09, 4.49, 36.84]}
                rotation={[-0.06, -0.17, -0.7]}
              />
            </group>
            <group rotation={[-0.16, 0.34, 0.86]}>
              <mesh
                geometry={nodes.Sphere_03_low003_Material_01_0.geometry}
                material={materials.Material_01}
                position={[-20.62, 9.16, 32.79]}
                rotation={[-0.16, -0.34, -0.86]}
              />
            </group>
            <mesh geometry={nodes.Sphere_04_low003_Material_01_0.geometry} material={materials.Material_01} position={[-10.87, -6.49, 39.81]} />
            <group position={[-13.74, -8.83, 40.46]} rotation={[-0.06, 0.18, 0.66]}>
              <mesh geometry={nodes.Sphere_05_low003_Material_01_0.geometry} material={materials.Material_01} rotation={[-0.06, -0.18, -0.66]} />
            </group>
            <group rotation={[-0.02, 0.07, 0.55]}>
              <mesh
                geometry={nodes.Sphere_06_low003_Material_01_0.geometry}
                material={materials.Material_01}
                position={[-22.83, 0.22, 39.42]}
                rotation={[-0.02, -0.07, -0.55]}
              />
            </group>
            <mesh geometry={nodes.Button_01_low003_Material_01_0.geometry} material={materials.Material_01} position={[8.61, 11.56, -23.91]} />
            <mesh geometry={nodes.Button_02_low003_Material_01_0.geometry} material={materials.Material_01} position={[-0.07, 12.22, -25.15]} />
            <mesh geometry={nodes.Button_03_low003_Material_01_0.geometry} material={materials.Material_01} position={[-8.72, 11.64, -23.29]} />
            <mesh geometry={nodes.Circle_02_low003_Material_01_0.geometry} material={materials.Material_01} position={[-1.83, 0.24, 35.8]} />
            <mesh geometry={nodes.Corps_01_low014_Material_01_0.geometry} material={materials.Material_01} position={[0, 0.04, 0.27]} />
            <mesh geometry={nodes.Corps_01_low015_Material_01_0.geometry} material={materials.Material_01} position={[0, 0.04, 0.27]} />
            <mesh geometry={nodes.Corps_01_low016_Material_01_0.geometry} material={materials.Material_01} position={[0.02, 7.74, 14.3]} />
            <mesh
              geometry={nodes.Metal_thread_01_low003_Material_01_0.geometry}
              material={materials.Material_01}
              position={[-19.38, -12.49, 35.66]}
            />
            <mesh geometry={nodes.Sphere_01_low003_Material_01_0.geometry} material={materials.Material_01} position={[-2.72, -0.49, 36.88]} />
            <mesh geometry={nodes.Sphere_02_low003_Material_01_0.geometry} material={materials.Material_01} position={[-6.02, -1.24, 37.44]} />
            <mesh geometry={nodes.Sphere_07_low003_Material_01_0.geometry} material={materials.Material_01} position={[-20.21, -12.68, 40.73]} />
            <mesh geometry={nodes.Sphere_08_low003_Material_01_0.geometry} material={materials.Material_01} position={[-23.63, -14.23, 39.99]} />
            <mesh geometry={nodes.Sphere_09_low003_Material_01_0.geometry} material={materials.Material_01} position={[-26.69, -15.62, 38.44]} />
            <mesh geometry={nodes.Sphere_10_low003_Material_01_0.geometry} material={materials.Material_01} position={[-29.5, -16.93, 36.28]} />
            <mesh geometry={nodes.Sphere_11_low003_Material_01_0.geometry} material={materials.Material_01} position={[-31.8, -18.26, 33.59]} />
            <mesh geometry={nodes.Sphere_12_low003_Material_01_0.geometry} material={materials.Material_01} position={[-32.76, -20.51, 30.78]} />
            <mesh geometry={nodes.Sphere_13_low003_Material_01_0.geometry} material={materials.Material_01} position={[-32.52, -23.75, 29.09]} />
            <mesh geometry={nodes.Sphere_14_low003_Material_01_0.geometry} material={materials.Material_01} position={[-30.13, -26.5, 29.15]} />
            <mesh geometry={nodes.Sphere_15_low003_Material_01_0.geometry} material={materials.Material_01} position={[-27.16, -27.97, 30.78]} />
            <mesh geometry={nodes.Sphere_16_low003_Material_01_0.geometry} material={materials.Material_01} position={[-24.28, -28.57, 33.12]} />
            <mesh geometry={nodes.Sphere_17_low003_Material_01_0.geometry} material={materials.Material_01} position={[-21.48, -28.59, 35.63]} />
            <mesh geometry={nodes.Sphere_18_low003_Material_01_0.geometry} material={materials.Material_01} position={[-18.72, -27.84, 38.11]} />
            <mesh geometry={nodes.Sphere_19_low003_Material_01_0.geometry} material={materials.Material_01} position={[-15.74, -26.69, 40.12]} />
            <mesh geometry={nodes.Sphere_20_low003_Material_01_0.geometry} material={materials.Material_01} position={[-12.69, -25.07, 41.4]} />
            <mesh geometry={nodes.Sphere_22_low003_Material_01_0.geometry} material={materials.Material_01} position={[-9.63, -22.95, 41.92]} />
            <mesh geometry={nodes.Sphere_23_low003_Material_01_0.geometry} material={materials.Material_01} position={[-6.99, -20.26, 41.75]} />
            <mesh geometry={nodes.Sphere_24_low003_Material_01_0.geometry} material={materials.Material_01} position={[-4.77, -17.23, 41.42]} />
            <mesh geometry={nodes.Sphere_25_low003_Material_01_0.geometry} material={materials.Material_01} position={[-2.95, -13.99, 40.87]} />
            <mesh geometry={nodes.Sphere_26_low003_Material_01_0.geometry} material={materials.Material_01} position={[-1.56, -10.58, 40.08]} />
            <mesh geometry={nodes.Sphere_27_low003_Material_01_0.geometry} material={materials.Material_01} position={[-0.76, -7.03, 39.11]} />
            <mesh geometry={nodes.Sphere_28_low003_Material_01_0.geometry} material={materials.Material_01} position={[-0.87, -3.46, 37.97]} />
          </group>
        </group>
      </group>
      {/* VHS Player - Tiny */}
      <group position={[-4.84, 7.87, 0.56]} rotation={[-Math.PI / 2, 0, 2.78]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[-177.66, -12.35, 154.9]} rotation={[-Math.PI / 2, 0, 0]} scale={[7.69, 8.05, 4.64]}>
            <mesh geometry={nodes.Cube001_Material007_0.geometry} material={materials["Material.017"]} />
            <mesh geometry={nodes.Cube001_Material007_0001.geometry} material={materials["Material.017"]} />
            <mesh geometry={nodes.Cube001_Material007_0002.geometry} material={materials["Material.017"]} />
            <mesh geometry={nodes.Cube001_Material_0.geometry} material={materials["Material.018"]} />
          </group>
          <instances.PlaneMaterial position={[-193.27, -28.02, 94.51]} rotation={[-0.8, -Math.PI / 2, 0]} scale={[2.22, 2.22, 0.63]} />
          <instances.PlaneMaterial position={[-193.27, -28.02, -138.47]} rotation={[-0.8, -Math.PI / 2, 0]} scale={[2.22, 2.22, 0.63]} />
          <instances.PlaneMaterial position={[-193.27, 46.93, 94.51]} rotation={[-0.8, -Math.PI / 2, 0]} scale={[2.22, 2.22, 0.63]} />
          <instances.PlaneMaterial position={[-193.27, 46.93, -138.47]} rotation={[-0.8, -Math.PI / 2, 0]} scale={[2.22, 2.22, 0.63]} />
          <mesh
            geometry={nodes.Plane004_Material006_0.geometry}
            material={materials["Material.019"]}
            position={[195.28, -28.02, -138.47]}
            rotation={[0.8, 1.57, 0]}
            scale={[2.22, 2.22, 0.63]}
          />
          <instances.PlaneMaterial position={[195.28, -28.02, 94.51]} rotation={[0.8, 1.57, 0]} scale={[2.22, 2.22, 0.63]} />
          <instances.PlaneMaterial position={[195.28, 46.93, -138.47]} rotation={[0.8, 1.57, 0]} scale={[2.22, 2.22, 0.63]} />
          <instances.PlaneMaterial position={[195.28, 46.93, 94.51]} rotation={[0.8, 1.57, 0]} scale={[2.22, 2.22, 0.63]} />
        </group>
      </group>
      {/* OLD TV RIGHT - Tiny */}
      <group position={[-4.71, 8.38, 0.89]} rotation={[-Math.PI / 2, 0, 1.24]} scale={0.26}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[5.95, 9.18, -4.53]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.01}>
            <mesh geometry={nodes.Object_171.geometry} material={materials["Material.043"]} />
            <mesh geometry={nodes.Object_172.geometry} material={materials["Material.043"]} />
          </group>
          <mesh geometry={nodes.Object_471.geometry} material={materials["Material.048"]} position={[0, 5.37, -0.07]} scale={[5.55, 4.7, 6.67]} />
          <mesh
            geometry={nodes.Object_477.geometry}
            material={materials["Material.036"]}
            position={[0, 5.37, -0.07]}
            rotation={[0, 0, Math.PI]}
            scale={[-5.55, -4.7, -6.67]}
          />
          <mesh
            geometry={nodes.Object_479.geometry}
            material={materials["Material.022"]}
            position={[0, 5.37, -0.07]}
            rotation={[0, 0, Math.PI]}
            scale={[-5.55, -4.7, -6.67]}
          />
          <mesh
            geometry={nodes.Object_481.geometry}
            material={materials["Material.048"]}
            position={[0, 5.37, -0.07]}
            rotation={[0, 0, Math.PI]}
            scale={[-5.55, -4.7, -6.67]}
          />
          <mesh geometry={nodes.Object_483.geometry} material={materials["Material.026"]} position={[0, 5.37, -0.07]} scale={[5.6, 4.75, 6.74]} />
          <mesh geometry={nodes.Object_485.geometry} material={materials["Material.051"]} position={[6.17, 1.68, 2.94]} scale={[5.66, 5.38, 7.62]} />
          <mesh geometry={nodes.Object_487.geometry} material={materials["Material.066"]} position={[6.17, 1.68, 4.03]} scale={[5.66, 5.38, 7.62]} />
          <mesh geometry={nodes.Object_489.geometry} material={materials["Material.067"]} position={[6.17, 1.68, 4.03]} scale={[5.66, 5.38, 7.62]} />
          <mesh geometry={nodes.Object_491.geometry} material={materials["Material.051"]} position={[6.17, 1.68, 5.13]} scale={[5.66, 5.38, 7.62]} />
          <mesh geometry={nodes.Object_493.geometry} material={materials["Material.049"]} position={[6.17, 1.68, 5.13]} scale={[5.66, 5.38, 7.62]} />
          <mesh geometry={nodes.Object_159.geometry} material={materials["Material.036"]} position={[0, 5.37, -0.07]} scale={[5.55, 4.7, 6.67]} />
          <mesh geometry={nodes.Object_161.geometry} material={materials["Material.025"]} position={[0, 5.37, -0.07]} scale={[5.6, 4.75, 6.74]} />
          <mesh geometry={nodes.Object_163.geometry} material={materials["Material.037"]} position={[0, 5.37, -0.07]} scale={[5.6, 4.75, 6.74]} />
          <mesh geometry={nodes.Object_165.geometry} material={materials["Material.038"]} position={[0, 5.37, -0.07]} scale={[5.6, 4.75, 6.74]} />
          <mesh geometry={nodes.Object_167.geometry} material={materials["Material.039"]} position={[5.94, 4.78, -4.54]} scale={[4.03, 3.41, 4.84]} />
          <mesh geometry={nodes.Object_169.geometry} material={materials["Material.040"]} position={[5.85, 4.92, -4.54]} scale={[2.9, 4.75, 6.74]} />
          <mesh geometry={nodes.Object_174.geometry} material={materials["Material.037"]} position={[0, 5.29, -0.07]} scale={[5.6, 4.75, 6.76]} />
          <mesh geometry={nodes.Object_176.geometry} material={materials["Material.041"]} position={[0, 5.29, -0.07]} scale={[5.6, 4.75, 6.76]} />
          <mesh geometry={nodes.Object_178.geometry} material={materials["Material.039"]} position={[0, 5.37, -0.07]} scale={[5.6, 4.75, 6.74]} />
          <mesh geometry={nodes.Object_180.geometry} material={materials["Material.039"]} position={[6.03, 1.68, 1.78]} scale={[4.74, 4.02, 5.7]} />
          <mesh geometry={nodes.Object_182.geometry} material={materials["Material.042"]} position={[6.17, 1.68, 2.94]} scale={[5.66, 5.38, 7.62]} />
          <mesh geometry={nodes.Object_184.geometry} material={materials["Material.044"]} position={[6.17, 1.68, 4.03]} scale={[5.66, 5.38, 7.62]} />
          <mesh geometry={nodes.Object_186.geometry} material={materials["Material.039"]} position={[6.07, 1.68, 5.13]} scale={[5.66, 5.38, 7.62]} />
          <mesh geometry={nodes.Object_188.geometry} material={materials["Material.042"]} position={[6.17, 1.68, 5.13]} scale={[5.66, 5.38, 7.62]} />
          <mesh geometry={nodes.Object_194.geometry} material={materials["Material.022"]} position={[6.33, 2.92, 1.38]} scale={[0.15, 0.17, 0.62]} />
          <mesh geometry={nodes.Object_196.geometry} material={materials["Material.039"]} position={[6.33, 2.92, 1.38]} scale={[0.15, 0.17, 0.62]} />
          <mesh geometry={nodes.Object_198.geometry} material={materials["Material.038"]} position={[0, 5.37, -0.07]} scale={[5.55, 4.7, 6.67]} />
          <mesh geometry={nodes.Object_200.geometry} material={materials["Material.038"]} position={[0, 5.37, -0.07]} />
          <mesh
            geometry={nodes.Object_202.geometry}
            material={materials["Material.022"]}
            position={[0.7, 0.32, 5.17]}
            rotation={[0, 1.57, 0]}
            scale={[0.23, 0.36, 0.2]}
          />
          <mesh geometry={nodes.Object_204.geometry} material={materials["Material.038"]} position={[0, 5.37, -0.07]} scale={[5.55, 4.7, 6.67]} />
          <mesh geometry={nodes.Object_206.geometry} material={materials.material_0} position={[0.04, 5.37, -0.07]} />
          <mesh
            geometry={nodes.Object_212.geometry}
            material={materials["Material.032"]}
            position={[-3.57, 5.57, -3.53]}
            scale={[5.52, 4.87, 7.22]}
          />
          <mesh geometry={nodes.Object_214.geometry} material={materials["Material.047"]} position={[0, 5.37, -0.07]} scale={[5.55, 4.7, 6.67]} />
          <mesh geometry={nodes.Object_216.geometry} material={materials["Material.047"]} position={[0, 5.37, -0.07]} scale={[5.55, 4.7, 6.67]} />
          <mesh geometry={nodes.Object_218.geometry} material={materials["Material.023"]} position={[0, 5.37, -0.07]} scale={[5.55, 4.7, 6.67]} />
          <mesh
            geometry={nodes.Object_220.geometry}
            material={materials["Material.021"]}
            position={[-3.14, 3.37, -3.84]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={[-0.28, -0.03, -0.21]}
          />
          <mesh geometry={nodes.Object_222.geometry} material={materials["Material.021"]} position={[0, 5.37, -0.07]} scale={[5.55, 4.7, 6.67]} />
          <mesh geometry={nodes.Object_224.geometry} material={materials["Material.048"]} position={[0, 5.37, -0.31]} scale={[5.55, 4.7, 6.67]} />
          <mesh geometry={nodes.Object_226.geometry} material={materials["Material.047"]} position={[0, 5.37, -0.31]} scale={[5.55, 4.7, 6.67]} />
          <mesh
            geometry={nodes.Object_228.geometry}
            material={materials["Material.043"]}
            position={[-0.17, 9.58, 6.08]}
            rotation={[-0.09, 0, 0]}
            scale={[0.08, 0.14, 0.14]}
          />
          <mesh
            geometry={nodes.Object_230.geometry}
            material={materials["Material.030"]}
            position={[-3.48, 7, -2.41]}
            rotation={[-0.41, 0, 0]}
            scale={[0.08, 0.14, 0.14]}
          />
          <mesh
            geometry={nodes.Object_232.geometry}
            material={materials.material_0}
            position={[-0.29, 9.67, -0.07]}
            rotation={[0.99, 0, 0]}
            scale={[0.06, 0.1, 0.1]}
          />
          <mesh
            geometry={nodes.Object_234.geometry}
            material={materials.material_0}
            position={[-0.29, 9.67, -0.07]}
            rotation={[0.99, 0, 0]}
            scale={[0.06, 0.1, 0.1]}
          />
          <mesh geometry={nodes.Object_236.geometry} material={materials["Material.025"]} position={[-3.48, 2.28, -1.75]} scale={[0.39, 1, 0.88]} />
          <mesh geometry={nodes.Object_238.geometry} material={materials["Material.025"]} position={[0, 5.37, -0.07]} scale={[5.55, 4.7, 6.67]} />
          <mesh
            geometry={nodes.Object_240.geometry}
            material={materials["Material.039"]}
            position={[-3.55, 2.27, -1.75]}
            scale={[0.09, 0.13, 0.17]}
          />
          <mesh geometry={nodes.Object_242.geometry} material={materials["Material.049"]} position={[5.84, 4.19, -4.54]} scale={[5.6, 4.75, 5.59]} />
          <mesh geometry={nodes.Object_244.geometry} material={materials["Material.039"]} position={[0, 5.37, -0.07]} scale={[5.6, 4.75, 6.74]} />
          <mesh geometry={nodes.Object_246.geometry} material={materials["Material.025"]} position={[0, 5.37, -0.07]} scale={[5.6, 4.75, 6.74]} />
          <mesh geometry={nodes.Object_248.geometry} material={materials["Material.039"]} position={[0, 5.37, -0.07]} scale={[5.6, 4.75, 6.74]} />
          <mesh geometry={nodes.Object_250.geometry} material={materials["Material.050"]} position={[0, 5.37, -0.07]} scale={[5.55, 4.7, 6.67]} />
          <mesh geometry={nodes.Object_252.geometry} material={materials["Material.025"]} position={[0, 5.37, -0.07]} scale={[5.55, 4.7, 6.67]} />
          <mesh geometry={nodes.Object_254.geometry} material={materials["Material.047"]} position={[0, 5.37, -0.07]} scale={[5.55, 4.7, 6.67]} />
          <mesh geometry={nodes.Object_256.geometry} material={materials["Material.022"]} position={[0, 5.37, -0.07]} scale={[5.6, 4.75, 6.74]} />
          <mesh geometry={nodes.Object_258.geometry} material={materials.material_0} position={[0, 5.37, -0.07]} scale={[5.6, 4.75, 6.74]} />
          <mesh geometry={nodes.Object_260.geometry} material={materials["Material.022"]} position={[5.94, 4.78, -4.54]} scale={[4.03, 3.41, 4.84]} />
          <mesh geometry={nodes.Object_262.geometry} material={materials["Material.039"]} position={[7.21, 3.52, -4.53]} />
          <mesh geometry={nodes.Object_264.geometry} material={materials["Material.049"]} position={[0, 5.37, -0.07]} scale={[5.6, 4.75, 6.74]} />
          <mesh geometry={nodes.Object_268.geometry} material={materials["Material.038"]} position={[0, 5.37, -0.07]} scale={[5.6, 4.75, 6.74]} />
          <mesh geometry={nodes.Object_270.geometry} material={materials["Material.039"]} position={[0, 5.37, -0.07]} scale={[5.6, 4.75, 6.74]} />
          <mesh geometry={nodes.Object_274.geometry} material={materials["Material.021"]} position={[0, 5.37, -0.07]} scale={[5.6, 4.75, 6.74]} />
          <mesh geometry={nodes.Object_276.geometry} material={materials["Material.049"]} position={[0, 5.29, -0.07]} scale={[5.6, 4.75, 6.76]} />
          <mesh geometry={nodes.Object_278.geometry} material={materials["Material.051"]} position={[0, 5.29, -0.07]} scale={[5.6, 4.75, 6.76]} />
          <mesh geometry={nodes.Object_284.geometry} material={materials["Material.021"]} position={[0, 5.37, -0.07]} scale={[5.6, 4.75, 6.74]} />
          <mesh geometry={nodes.Object_286.geometry} material={materials["Material.046"]} position={[0, 5.37, -0.07]} scale={[5.55, 4.7, 6.67]} />
          <mesh geometry={nodes.Object_288.geometry} material={materials["Material.039"]} position={[0, 5.37, -0.07]} scale={[5.6, 4.75, 6.74]} />
          <mesh geometry={nodes.Object_290.geometry} material={materials["Material.022"]} position={[0, 5.37, -0.07]} scale={[5.55, 4.7, 6.67]} />
          <mesh geometry={nodes.Object_292.geometry} material={materials["Material.030"]} position={[0, 5.37, -0.07]} scale={[5.55, 4.7, 6.67]} />
          <mesh geometry={nodes.Object_294.geometry} material={materials["Material.022"]} position={[0, 5.37, -0.07]} scale={[5.55, 4.7, 6.67]} />
          <mesh geometry={nodes.Object_296.geometry} material={materials["Material.022"]} position={[0, 5.37, -0.07]} />
          <mesh geometry={nodes.Object_453.geometry} material={materials["Material.036"]} position={[0, 5.37, -0.07]} scale={[5.55, 4.7, 6.67]} />
          <mesh geometry={nodes.Object_455.geometry} material={materials["Material.022"]} position={[0, 5.37, -0.07]} scale={[5.55, 4.7, 6.67]} />
          <mesh
            geometry={nodes.Object_461.geometry}
            material={materials["Material.038"]}
            position={[-1.72, 5.64, 5.04]}
            rotation={[0, -0.01, 0]}
            scale={[5.55, 4.75, 6.67]}
          />
          <instances.Object88 position={[-1.96, 8.54, -3.84]} rotation={[0, 0, 0.18]} scale={[0.33, 0.18, 0.33]} />
          <instances.Object88 position={[-1.96, 8.54, -2.73]} rotation={[0, 0, 0.18]} scale={[0.33, 0.18, 0.33]} />
          <mesh geometry={nodes.Object_190.geometry} material={materials["Material.025"]} position={[0, 5.37, -0.07]} />
          {/* <mesh geometry={nodes.Object_192.geometry} material={materials.SCREEN} position={[8.23, 5.83, 1.37]} rotation={[0, 0, -Math.PI / 2]} scale={[2.81, 2.32, 3.58]} /> */}
          <Screen
            panel="Object_192"
            content={screenContent.rightMiddleScreen}
            position={[8.23, 5.83, 1.37]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={[2.81, 2.32, 3.58]}
          />
          <mesh geometry={nodes.Object_272.geometry} material={materials["Material.026"]} position={[0, 5.37, -0.07]} />
          <mesh
            geometry={nodes.Object_280.geometry}
            material={materials["Material.037"]}
            position={[5.98, 5.94, -4.53]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={[0.11, 1, 1.11]}
          />
          <mesh
            geometry={nodes.Object_266.geometry}
            material={materials["Material.039"]}
            position={[6.43, 2.93, 1.38]}
            rotation={[Math.PI / 2, -0.2, -Math.PI / 2]}
            scale={[0.47, 0.47, 0.27]}
          />
          <mesh
            geometry={nodes.Object_282.geometry}
            material={materials["Material.039"]}
            position={[5.99, 5.94, -4.55]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
            scale={[0.37, 0.35, 0.17]}
          />
        </group>
      </group>
      {/* TECH PACK - Small */}
      <group position={[16.67, 11.14, 0]} rotation={[-Math.PI / 2, 0, 0]}>
        {/* Small TV Left Left */}
        <group position={[-11.88, -0.3, -1.69]} rotation={[0, 0, 0.2]} scale={0.94}>
          <instances.Cube />
          <instances.Cube1 />
          {/* <mesh geometry={nodes.Cube011_2.geometry} material={materials.SCREEN} /> */}
          <Screen panel="Cube011_2" content={screenContent.leftLeftScreen} />
          <instances.Cube3 />
          <instances.Cube4 />
          <instances.Cube5 />
          <instances.Cube6 />
        </group>
        {/* Small TV Left Right */}
        <group position={[-13.99, -1, -1.69]} rotation={[0, 0, 0.38]} scale={0.94}>
          <instances.Cube />
          <instances.Cube1 />
          <instances.Cube3 />
          <instances.Cube4 />
          <instances.Cube5 />
          <instances.Cube6 />
          {/* <mesh geometry={nodes.Cube008_2.geometry} material={materials.SCREEN} /> */}
          <Screen panel="Cube011_2" content={screenContent.leftRightScreen} />
        </group>
        {/* Small TV Top */}
        <group position={[-13.06, -0.83, 0.54]} rotation={[0, 0, 0.59]} scale={0.94}>
          <instances.Cube />
          <instances.Cube1 />
          <instances.Cube3 />
          <instances.Cube4 />
          <instances.Cube5 />
          <instances.Cube6 />
          {/* <mesh geometry={nodes.Cube012_2.geometry} material={materials.SCREEN} /> */}
          <Screen panel="Cube011_2" content={screenContent.leftUpperScreen} />
        </group>
        <group position={[-23.94, 0.85, -2.72]} rotation={[0, 0, -0.35]} scale={0.79}>
          <mesh geometry={nodes.Cube027_0.geometry} material={materials["Material.074"]} />
          <mesh geometry={nodes.Cube027_1.geometry} material={materials["Material.069"]} />
          <mesh geometry={nodes.Cube027_2.geometry} material={materials["Material.071"]} />
          <mesh geometry={nodes.Cube027_3.geometry} material={materials["Material.075"]} />
          <mesh geometry={nodes.Cube027_4.geometry} material={materials["Material.070"]} />
          <mesh geometry={nodes.Cube027_5.geometry} material={materials["Material.068"]} />
          <mesh geometry={nodes.Cube027_6.geometry} material={materials["Material.073"]} />
          <mesh geometry={nodes.Cube027_7.geometry} material={materials["Material.076"]} />
          <mesh geometry={nodes.Cube027_8.geometry} material={materials["Material.088"]} />
        </group>
        <group position={[-17.32, -2.02, -1.37]} scale={1.74}>
          {/* <mesh geometry={nodes.BigTVScreen.geometry} material={materials.SCREEN} /> */}
          <Screen panel="BigTVScreen" content={screenContent.middleScreen} />
          <mesh geometry={nodes.Cube051_0.geometry} material={materials["Material.069"]} />
          <mesh geometry={nodes.Cube051_1.geometry} material={materials["Material.070"]} />
          <mesh geometry={nodes.Cube051_2.geometry} material={materials["Material.068"]} />
          <mesh geometry={nodes.Cube051_3.geometry} material={materials["Material.073"]} />
          <mesh geometry={nodes.Cube051_5.geometry} material={materials["Material.076"]} />
          <mesh geometry={nodes.Cube051_6.geometry} material={materials["Material.088"]} />
          <mesh geometry={nodes.Cube051_7.geometry} material={materials["Material.097"]} />
        </group>
        <group position={[-24.47, 1.2, -1.18]} scale={0.31}>
          <mesh geometry={nodes.Cube052_0.geometry} material={materials["Material.068"]} />
          <mesh geometry={nodes.Cube052_1.geometry} material={materials["Material.081"]} />
          <mesh geometry={nodes.Cube052_2.geometry} material={materials["Material.089"]} />
        </group>
        <group position={[-24.25, 0.58, -0.94]} rotation={[0, 0, -0.56]} scale={[0.59, 0.59, 0.73]}>
          <mesh geometry={nodes.Cube009_0.geometry} material={materials["Material.068"]} position={[0.05, -0.22, -0.23]} />
          <mesh geometry={nodes.Cube009_1.geometry} material={materials["Material.090"]} position={[0.05, -0.22, -0.23]} />
          <mesh geometry={nodes.Cube009_2.geometry} material={materials["Material.089"]} position={[0.05, -0.22, -0.23]} />
        </group>
        <group position={[4.49, -7.52, 1.97]} rotation={[0, 0, 2.79]} scale={0.99}>
          <mesh geometry={nodes.Cylinder_0.geometry} material={materials["Material.091"]} position={[16.69, -3.78, -5.75]} />
          <mesh geometry={nodes.Cylinder_1.geometry} material={materials["Material.070"]} position={[16.69, -3.78, -5.75]} />
          <mesh geometry={nodes.Cylinder_2.geometry} material={materials["Material.092"]} position={[16.69, -3.78, -5.75]} />
          <mesh geometry={nodes.Cylinder_3.geometry} material={materials["Material.086"]} position={[16.69, -3.78, -5.75]} />
          <mesh geometry={nodes.Cylinder_4.geometry} material={materials["Material.069"]} position={[16.69, -3.78, -5.75]} />
          <mesh geometry={nodes.Cylinder_5001.geometry} material={materials["Material.073"]} position={[16.69, -3.78, -5.75]} />
        </group>
        <group position={[-23.77, 0.87, -1.22]} rotation={[0, 0, -0.07]} scale={[0.6, 0.6, 0.3]}>
          <mesh geometry={nodes.Cube007_0.geometry} material={materials["Material.069"]} />
          <mesh geometry={nodes.Cube007_1.geometry} material={materials["Material.068"]} />
          <mesh geometry={nodes.Cube007_2.geometry} material={materials["Material.070"]} />
          <mesh geometry={nodes.Cube007_3.geometry} material={materials["Material.089"]} />
        </group>
      </group>
      {/* Panasonic TV - Small */}
      <group position={[-0.59, 11.52, 0.24]} rotation={[-Math.PI / 2, 0, 3.13]} scale={0.06}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 26.84, 0]}>
            <mesh
              geometry={nodes.defaultMaterial006.geometry}
              material={materials.TVfront}
              position={[11.06, -26.3, -18.65]}
              rotation={[-Math.PI, 0, -Math.PI]}
            />
            <mesh geometry={nodes.defaultMaterial005.geometry} material={materials.TVfront} position={[0, -26.84, 0]} />
            <mesh
              geometry={nodes.defaultMaterial007.geometry}
              material={materials.TVfront}
              position={[26.91, -17.62, -17.22]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
              scale={[0.17, 0.16, 0.17]}
            />
            <mesh geometry={nodes.defaultMaterial002.geometry} material={materials.TVfront} />
            <mesh geometry={nodes.defaultMaterial001.geometry} material={materials.TVfront} />
            <mesh geometry={nodes.defaultMaterial008.geometry} material={materials.TVfront} position={[0, -19.83, 0.85]} scale={0.11} />
            <mesh geometry={nodes.defaultMaterial.geometry} material={materials.TVback} position={[0, -0.04, 0]} scale={[0.99, 0.99, 1]} />
            {/* <mesh geometry={nodes.defaultMaterial003.geometry} material={materials.TVScreen} position={[0, 0, -166.62]} scale={398.22} /> */}
            <Screen panel="defaultMaterial003" content={screenContent.middleUpperScreen} position={[0, 0, -166.62]} scale={398.22} />
            <mesh
              geometry={nodes.defaultMaterial004.geometry}
              material={materials.TVfront}
              position={[3.17, -20.05, -18.3]}
              rotation={[0, 0, -0.6]}
              scale={[0.38, 0.38, 0.22]}
            />
          </group>
        </group>
      </group>
      {/* Keyboard - Tiny */}
      <group position={[-0.43, 7.62, -2.09]} rotation={[-Math.PI / 2, 0, -3.05]} scale={[0.52, 0.52, 0.58]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[-18.34, -0.8, -74.23]}>
            <group position={[-119.15, 21.25, -259.44]}>
              <instances.CylindreMat position={[77.97, -27.12, 210.5]} rotation={[0, 0, -Math.PI]} />
              <mesh geometry={nodes.Cylindre_1_Mat3_0.geometry} material={materials["Mat.3"]} position={[106.6, -22.82, 184.55]} />
              <mesh
                geometry={nodes.Cylindre_2_Mat3_0.geometry}
                material={materials["Mat.3"]}
                position={[77.97, -27.2, 185.98]}
                rotation={[0, 0, Math.PI]}
              />
              <mesh
                geometry={nodes.Cylindre_2_2_Mat3_0.geometry}
                material={materials["Mat.3"]}
                position={[106.6, -22.33, 203.33]}
                rotation={[0.05, 0, 0]}
              />
              <mesh geometry={nodes["Extrusion_contr��l��e_Mat3_0"].geometry} material={materials["Mat.3"]} position={[115.75, -28.4, 4.67]} />
              <mesh geometry={nodes["Extrusion_contr��l��e_1_Mat3_0"].geometry} material={materials["Mat.3"]} position={[100.63, -27.11, 4.55]} />
            </group>
            <instances.BoolenMat position={[-343.87, -3.78, 28.02]} />
            <instances.BoolenMat position={[-12.53, -3.33, -38.94]} rotation={[0, -1.57, 0]} />
            <mesh geometry={nodes.Cube_Mat6_0.geometry} material={materials["Mat.6_0"]} position={[165.17, 35.62, -27.54]} rotation={[-1.57, 0, 0]} />
            <mesh geometry={nodes.Cube_1_2_Mat3_0.geometry} material={materials["Mat.3_0"]} position={[363.87, -11.55, 203.87]} />
            <mesh geometry={nodes.Cube_2_Mat3_0.geometry} material={materials["Mat.3_0"]} position={[-341.1, -7.94, 67.52]} />
            <mesh
              geometry={nodes["Cube_2_2_Mat6_(converted)_(converted_from_U-Render)_0"].geometry}
              material={materials["Mat.6_converted_converted_from_U-Render_1"]}
              position={[257.91, -15.85, 195.89]}
            />
            <mesh
              geometry={nodes["Cube_3_Mat6_(converted)_(converted_from_U-Render)_0"].geometry}
              material={materials["Mat.6_converted_converted_from_U-Render_1"]}
              position={[184.39, 34.78, -25.1]}
              rotation={[-1.57, 0, 0]}
            />
            <mesh
              geometry={nodes.Cube_4_Mat12_0.geometry}
              material={materials["Mat.12"]}
              position={[129.57, -1.73, -51.68]}
              scale={[1.35, 1.38, 1.35]}
            />
            <mesh geometry={nodes.Cube_5_Mat3_0.geometry} material={materials["Mat.3_0"]} position={[125.63, -1.73, -47.18]} scale={[1, 1.21, 1]} />
            <mesh
              geometry={nodes.Cube_6_VOLUME_0.geometry}
              material={materials.VOLUME}
              position={[129.57, -1.73, -51.68]}
              scale={[1.35, 1.38, 1.35]}
            />
            <mesh
              geometry={nodes.Cube_7_Cylindre_11_Mat3_0.geometry}
              material={materials["Mat.3_0"]}
              position={[-41.53, -8.83, -45.59]}
              rotation={[0, -1.57, 0]}
            />
            <mesh
              geometry={nodes.Cube_Cloneur_Cu_1_Extrusion_Cube_Cube_Mat3_0.geometry}
              material={materials["Mat.3_0"]}
              position={[315.75, 2.55, 175.93]}
              rotation={[-1.57, 0, 0]}
            />
            <mesh
              geometry={nodes.Cube_Cloneur_Cu_Ext_Mat3_0.geometry}
              material={materials["Mat.3"]}
              position={[18.34, 0.8, 74.23]}
              rotation={[-1.57, 0, 0]}
            />
            <mesh
              geometry={nodes.Cube_Cloneur_Cu_Extrusio_Mat3_0.geometry}
              material={materials["Mat.3_0"]}
              position={[18.34, 0.8, 74.23]}
              rotation={[-1.57, 0, 0]}
            />
            <mesh
              geometry={nodes.Cube_Cloneur_Cu_Extrusion_Cube_1_Extrusion_1_Mat3_0.geometry}
              material={materials["Mat.3_0"]}
              position={[-355.01, -18.32, 55.8]}
              rotation={[-1.57, 0, 0]}
            />
            <mesh
              geometry={nodes.Cube_Cloneur_Cu_Extrusion_Cube_4_Extrusion_1_Cube_Mat6_0.geometry}
              material={materials["Mat.6"]}
              position={[-231.78, 35.79, -27.54]}
              rotation={[-1.57, 0, 0]}
            />
            <mesh
              geometry={nodes.Cube_Cloneur_Cube_Extrusion_1_Cube_1_Mat1_0.geometry}
              material={materials["Mat.1"]}
              position={[315.41, 33.41, 88.97]}
              rotation={[-1.57, 0, 0]}
            />
            <mesh geometry={nodes.Cylindre_10_VOLUME_0.geometry} material={materials.VOLUME} position={[184.68, -4.38, -33.88]} />
            <mesh
              geometry={nodes.Cylindre_11_Mat4_0.geometry}
              material={materials["Mat.4"]}
              position={[-41.31, -5.97, -46.47]}
              rotation={[0, -1.57, 0]}
            />
            <mesh geometry={nodes.Cylindre_1_Extrusion_Cube_Mat3_0.geometry} material={materials["Mat.3_0"]} position={[-346.23, -1.69, 28.02]} />
            <mesh
              geometry={nodes.Cylindre_1_Extrusion_Cube_1_Extrusion_4_Mat3_0.geometry}
              material={materials["Mat.3_0"]}
              position={[-12.53, -1.24, -41.3]}
              rotation={[0, -1.57, 0]}
            />
            <mesh geometry={nodes.Cylindre_2_4_Mat3_0.geometry} material={materials["Mat.3"]} position={[-68.16, -6.65, -68.17]} />
            <instances.CylindreMat position={[-22.03, 16.3, -378.8]} rotation={[-Math.PI, 0, 0]} />
            <mesh
              geometry={nodes.Cylindre_4_Mat3_0.geometry}
              material={materials["Mat.3"]}
              position={[-22.03, 16.22, -354.28]}
              rotation={[-Math.PI, 0, 0]}
            />
            <mesh
              geometry={nodes["Cylindre_4_3_Mat6_(converted)_(converted_from_U-Render)_0"].geometry}
              material={materials["Mat.6_converted_converted_from_U-Render_0"]}
              position={[-68.16, -6.73, -40.96]}
            />
            <mesh geometry={nodes.Cylindre_5_Mat3_0.geometry} material={materials["Mat.3_0"]} position={[184.68, -4.38, -33.25]} />
            <mesh geometry={nodes.Cylindre_9_Mat4_0.geometry} material={materials["Mat.4"]} position={[-338.42, -8.14, 67.58]} />
            <mesh geometry={nodes.Cylindre_Cylindre_10_Mat4_0.geometry} material={materials["Mat.4"]} position={[-347.29, -12.58, 102.61]} />
            <mesh geometry={nodes.Cylindre_Extrusion_1_Mat4_0.geometry} material={materials["Mat.4"]} position={[392, -23.29, 102.82]} />
            <mesh geometry={nodes.Extrusion_1_2_Mat3_0.geometry} material={materials["Mat.3"]} position={[18.34, 0.8, 74.23]} />
            <mesh geometry={nodes.Extrusion_2_Mat3_0.geometry} material={materials["Mat.3"]} position={[18.34, 0.8, 74.23]} />
            <mesh geometry={nodes.Extrusion_2_2_Mat3_0.geometry} material={materials["Mat.3"]} position={[18.34, 0.8, 74.23]} />
            <mesh geometry={nodes.Extrusion_3_Mat3_0.geometry} material={materials["Mat.3"]} position={[-153.51, 0.8, 74.23]} />
            <mesh geometry={nodes.Extrusion_4_Mat3_0.geometry} material={materials["Mat.3"]} position={[-153.51, 0.8, 74.23]} />
            <mesh geometry={nodes.Extrusion_5_Mat3_0.geometry} material={materials["Mat.3"]} position={[-153.51, 0.8, 74.23]} />
            <mesh geometry={nodes.Extrusion_6_Mat3_0.geometry} material={materials["Mat.3"]} position={[-153.51, 0.8, 74.23]} />
            <mesh geometry={nodes.Extrusion_6_Cube_Mat3_0.geometry} material={materials["Mat.3_0"]} position={[-68.16, -10.44, -51.87]} />
            <mesh geometry={nodes.Extrusion_6_Cube_6_Mat3_0.geometry} material={materials["Mat.3"]} position={[-68.16, -10.44, -51.87]} />
            <mesh geometry={nodes["Extrusion_contr��l��e_1_2_Mat3_0"].geometry} material={materials["Mat.3"]} position={[64.76, 2.46, -136.66]} />
            <mesh geometry={nodes.Extrusion_Cylindre_Mat3_0.geometry} material={materials["Mat.3_0"]} position={[18.34, 0.8, 74.23]} />
            <mesh
              geometry={nodes.Extrusion_Extrusion_1_E_Cloneur_Mat3_0.geometry}
              material={materials["Mat.3_0"]}
              position={[18.34, -26.83, 74.25]}
            />
            <mesh geometry={nodes.PCB_Mat5_0.geometry} material={materials["Mat.5"]} position={[18.34, -1.26, 74.23]} />
            <mesh geometry={nodes.PCB_1_Mat9_0.geometry} material={materials["Mat.9"]} position={[18.34, -1.26, 74.23]} />
            <mesh geometry={nodes.TOUCHE_6128_Mat2_0.geometry} material={materials["Mat.2"]} position={[18.34, 0.8, 74.23]} />
          </group>
        </group>
      </group>
      {/* GPU - Tiny */}
      <group position={[-5.06, 11.55, -0.06]} rotation={[3.1, 0.34, -1.34]} scale={0.36}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_27.geometry} material={materials.Metal2} />
          <mesh geometry={nodes.Object_11003.geometry} material={materials.MainPCB} />
          <mesh geometry={nodes.Object_32001.geometry} material={materials["Material.100"]} />
          <mesh geometry={nodes.Object_33.geometry} material={materials.Metal2} />
          <mesh geometry={nodes.Object_35001.geometry} material={materials.MainPCB} />
          <mesh geometry={nodes.Object_37.geometry} material={materials.RedWire} />
          <mesh geometry={nodes.Object_38001.geometry} material={materials.BlackWire} />
          <mesh geometry={nodes.Object_25.geometry} material={materials.Metal2} />
          <mesh geometry={nodes.Object_21001.geometry} material={materials.MetalTubes} />
          <mesh geometry={nodes.Object_16001.geometry} material={materials.MainPCB} />
          <mesh geometry={nodes.Object_4.geometry} material={materials.MainPCB} />
          <mesh geometry={nodes.Object_5003.geometry} material={materials.BackPCB} />
          <mesh geometry={nodes.Object_23002.geometry} material={materials.Metal2} />
          <mesh geometry={nodes.Object_13001.geometry} material={materials["Material.098"]} />
          <mesh geometry={nodes.Object_14002.geometry} material={materials.MainPCB} />
          <mesh geometry={nodes.Object_18.geometry} material={materials["Material.099"]} />
          <mesh geometry={nodes.Object_19001.geometry} material={materials["Material.100"]} />
          <mesh geometry={nodes.Object_7002.geometry} material={materials.MainPCB} />
          <mesh geometry={nodes.Object_29001.geometry} material={materials["Material.100"]} />
          <mesh geometry={nodes.Object_30.geometry} material={materials.Metal2} />
          <mesh geometry={nodes.Object_9001.geometry} material={materials.MainPCB} />
        </group>
      </group>
      {/* VHS Pile - Tiny */}
      <group position={[4.58, 7.41, -2.93]} rotation={[-Math.PI / 2, 0, -2.35]} scale={9.16}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[19.72, 1.32, 1.95]} rotation={[Math.PI, -1.13, Math.PI]}>
            <group position={[-0.01, 1.16, 0.02]}>
              <mesh geometry={nodes["Plane008_02_-_Default_0"].geometry} material={materials["02_-_Default"]} />
              <mesh geometry={nodes["Plane008_09_-_Default_0"].geometry} material={materials["09_-_Default"]} />
              <mesh geometry={nodes.Plane008_default_0.geometry} material={materials["default"]} />
            </group>
          </group>
        </group>
      </group>
      {/* Radio Scanner - Small */}
      <group position={[-7.6, 9.56, -0.4]} rotation={[-Math.PI / 2, 0, -1.97]} scale={1.38}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial012.geometry} material={materials["kropp.001"]} />
          <mesh geometry={nodes.defaultMaterial011.geometry} material={materials["Knappar.001"]} />
        </group>
      </group>
      {/* Matrix TV Body */}
      <group position={[-3.88, 9.84, 0.22]} rotation={[-Math.PI / 2, 0, 1.22]} scale={1.03}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            geometry={nodes.Cylinder_1_0.geometry}
            material={materials["material.001"]}
            position={[58.7, 162.17, -67.14]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={[1.23, 1.23, 1.72]}
          />
        </group>
      </group>
      {/* Matrix TV Screen */}
      <group position={[-3.88, 9.84, 0.22]} rotation={[-Math.PI / 2, 0, 1.22]} scale={1.03}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          {/* <mesh geometry={nodes.Cylinder_1_0001.geometry} material={materials.SCREEN} position={[58.7, 162.17, -67.14]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[1.23, 1.23, 1.72]} /> */}
          <Screen
            panel="Cylinder_1_0001"
            content={screenContent.rightUpperScreen}
            position={[58.7, 162.17, -67.14]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={[1.23, 1.23, 1.72]}
          />
        </group>
      </group>
      {/* Cable */}
      {/* <mesh geometry={nodes.Cable.geometry} material={materials['Material.022']} position={[6.45, 7.45, -0.98]} rotation={[0, -1.55, 0]} /> */}
    </group>
  );
}

function Screen({ panel, content, children, ...props }: { panel: string; content: ScreenContent; children: JSX.Element; props?: any }): JSX.Element {
  if (content === null) return <></>;
  if (content?.type === "video") {
    return <ScreenWithVideo panel={panel} content={content} {...props} />;
  }
  if (content?.type === "scene") {
    return <ScreenWithScene panel={panel} content={content} {...props} />;
  }
  return (
    <ScreenWrapper panel={panel} {...props}>
      {children}
    </ScreenWrapper>
  );
}

function ScreenWrapper({ panel, children, ...props }: { panel: string; children: JSX.Element; props?: any }): JSX.Element {
  const { nodes } = useGLTF("/goatloaf_scene-transformed.glb");
  return (
    <group {...props}>
      <mesh castShadow geometry={nodes[panel].geometry}>
        {children}
      </mesh>
    </group>
  );
}

function ScreenWithVideo({ panel, content, ...props }: { panel: string; content: ScreenContent; props?: any }): JSX.Element {
  const texture = useVideoTexture(content.src, {});
  texture.flipY = false;
  return (
    <ScreenWrapper panel={panel} {...props}>
      <meshBasicMaterial map={texture} />
    </ScreenWrapper>
  );
}

function ScreenWithScene({ panel, content, ...props }: { panel: string; content: ScreenContent; props?: any }): JSX.Element {
  return (
    <ScreenWrapper panel={panel} {...props}>
      <meshBasicMaterial toneMapped={false}>
        <RenderTexture width={512} height={512} attach="map" anisotropy={16}>
          <PerspectiveCamera makeDefault manual aspect={1 / 1} position={[0, 0, 10]} />
          <color attach="background" args={["orange"]} />
          <ambientLight intensity={0.2} />
          <pointLight position={[10, 10, 10]} intensity={0.75} />
          <pointLight position={[-10, -10, -10]} />
          <SpinningBox position={[0, 0, 0]} scale={1} />
        </RenderTexture>
      </meshBasicMaterial>
    </ScreenWrapper>
  );
}

useGLTF.preload("/goatloaf_scene-transformed.glb");
